version: '3'
services:
  flask:
    build: .
  nginx:
    image: nginx
    ports: 
      - "2467:2467"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - flask